import 'dart:math';

const _prompts = [
  "What moment today made you feel most alive?",
  "Describe a small win you had today.",
  "What's one thing you'd like to remember from this week?",
  "If your day had a title, what would it be?",
  "What are you grateful for right now?",
  "What challenged you today, and how did you handle it?",
  "Write a letter to your future self.",
  "What's a decision you're wrestling with?",
  "Describe a conversation that stuck with you.",
  "What does your ideal morning look like?",
  "What's something you learned recently?",
  "How are you feeling, really?",
  "What's a memory that makes you smile?",
  "What's taking up too much mental space?",
  "What would you do if you weren't afraid?",
  "Describe your environment right now in detail.",
  "What's a habit you want to build?",
  "What's something you accomplished that you didn't celebrate?",
  "Who has influenced you recently?",
  "What does success look like to you?",
  "What's a boundary you need to set?",
  "What are you looking forward to?",
  "What's a question you're trying to answer?",
  "Describe a place that feels like home.",
  "What would you tell your younger self?",
  "What's something beautiful you noticed today?",
  "How do you recharge?",
  "What's a risk you're glad you took?",
  "What's a belief you've changed your mind about?",
  "What does your body need right now?",
  "What's something you've been procrastinating on?",
  "Describe a person who shaped you.",
  "What's your relationship with rest?",
  "What would make today a good day?",
  "What's a pattern you notice in your life?",
  "What are you protecting yourself from?",
  "What does freedom mean to you?",
  "What's something you want to let go of?",
  "What's a skill you'd like to develop?",
  "Describe a perfect hour.",
  "What's something you're curious about?",
  "What does your intuition tell you?",
  "What's a story you tell yourself?",
  "How do you want to feel tomorrow?",
  "What's something you'd like to be forgiven for?",
  "What's a tradition you cherish?",
  "What would you do with an empty day?",
  "What's a compliment you remember?",
  "What's something you've created that you're proud of?",
  "What does love look like in your daily life?",
];

final _rng = Random();

String randomPrompt() => _prompts[_rng.nextInt(_prompts.length)];
