[package]
name = "lumen_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "lumen_core"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
aes-gcm = "0.10"
argon2 = "0.5"
lazy_static = "1.4"
